### ISSUE TITLE
unable to disabled about?

### ISSUE THREAD

**Issue by iCrawl** [Gawdl3y/discord-graf#3]
https://github.com/Gawdl3y/discord-graf/blob/master/src/bot/index.js#L284
`[options.about=true] - Whether or not to register the built-in about command`

if you do 
`.registerDefaults({ about: false })`
in your code it won't disable it, even tho it should be able to be disabled?

It works of course when I modify the source and set the flag to false myself.

**Comment by Gawdl3y** [comment]
You have to use `registerDefaultCommands` and `registerDefaultModules`.
